<a href="https://colab.research.google.com/github/JoelRomero123/datawarehouse-seguros/blob/main/Clientes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
url="https://raw.githubusercontent.com/JoelRomero123/datawarehouse-seguros/refs/heads/main/data/clientes.csv"

BLOQUE 1:CARGA DEL DATASET

In [1]:
import pandas as pd

In [18]:
df=pd.read_csv(url)

Data set cargado corretamente

In [19]:
#LECTURA DEL ARCHIVO
display(df.head())

,id_cliente,nombre,email,genero,fecha_nacimiento,ciudad,segmento
0,1,José Chávez Pérez,jose.chavez.perez1@gmail.com,Hombre,2011/11/24,SanMiguel,NaN
1,2,Daniela Rojas Ortiz,daniela.rojas.ortiz2@seguro.sv,NaN,01-02-80,Sta. Ana,NaN
2,3,Ricardo Cruz Flores,ricardo.cruz.flores3@example.com,Masculino,06-18-79,S. Miguel,NaN
3,4,María Pérez Pérez,maria.perez.perez4@correo.com,Masculino,1960-09-29,LaLibertad,REGULAR
4,5,Fernanda Chávez Rojas,fernanda.chavez.rojas5@seguro.sv,NaN,1945/08/02,San Salvador,Pyme

BLOQUE 2: EXPLORACION DEL DATA SET

In [20]:
print("primeras filas del dataset")
display(df.head())

primeras filas del dataset

,id_cliente,nombre,email,genero,fecha_nacimiento,ciudad,segmento
0,1,José Chávez Pérez,jose.chavez.perez1@gmail.com,Hombre,2011/11/24,SanMiguel,NaN
1,2,Daniela Rojas Ortiz,daniela.rojas.ortiz2@seguro.sv,NaN,01-02-80,Sta. Ana,NaN
2,3,Ricardo Cruz Flores,ricardo.cruz.flores3@example.com,Masculino,06-18-79,S. Miguel,NaN
3,4,María Pérez Pérez,maria.perez.perez4@correo.com,Masculino,1960-09-29,LaLibertad,REGULAR
4,5,Fernanda Chávez Rojas,fernanda.chavez.rojas5@seguro.sv,NaN,1945/08/02,San Salvador,Pyme

In [21]:
print("Dimensiones del dataset(filas,columnas)")
print(df.shape)

Dimensiones del dataset(filas,columnas)
(3030, 7)

In [23]:
print("Nombres de las columnas")
print(df.columns)

Nombres de las columnas
Index(['id_cliente', 'nombre', 'email', 'genero', 'fecha_nacimiento', 'ciudad',
       'segmento'],
      dtype='object')

In [24]:
print("Tipos de datos de las columnas")
print(df.dtypes)

Tipos de datos de las columnas
id_cliente           int64
nombre              object
email               object
genero              object
fecha_nacimiento    object
ciudad              object
segmento            object
dtype: object

In [26]:
print("valores nulos por columna")
print(df.isnull().sum())

valores nulos por columna
id_cliente            0
nombre                0
email                 0
genero              595
fecha_nacimiento      0
ciudad                0
segmento            597
dtype: int64

In [28]:
print("Registros duplicados")
print(df.duplicated().sum())
#

Registros duplicados
0

BLOQUE 3: LIMPIEZA DE DATOS

In [29]:
#ELIMINAR ESPACIOS AL INICIO Y AL FINAL EN COLUMNAS DE TEXTO
for col in df.select_dtypes(include=['object']):
    df[col] = df[col].str.strip()

In [30]:
#Normalizar el nombre
df["nombre"]=df["nombre"].str.title()

In [32]:
#Normalizar el email
df["email"]=df["email"].str.lower()

In [33]:
#Normalizar genero
df["genero"]=df["genero"].str.upper()

In [38]:
df['fecha_nacimiento'] = pd.to_datetime(df['fecha_nacimiento'], errors='coerce')

In [39]:
#Normalizar ciudad
df['ciudad']=df['ciudad'].str.title()
#limpieza de segmento
df['ciudad']=df["ciudad"].astype(str)
df['ciudad']=df["ciudad"].str.strip()
df['ciudad']=df["ciudad"].str.upper()

In [37]:
#limpieza de segmento
df['segmento']=df["segmento"].astype(str)
df['segmento']=df["segmento"].str.strip()
df['segmento']=df["segmento"].str.upper()

BLOQUE 4: VALIDACION DE DATOS

In [40]:
 df["MOTIVO DE RECHAZO"]= ""
 df.loc[df['id_cliente']],pd.isnull,isnull()